import "@/app/ui/globals.css";
import type { Metadata } from "next";
import { inter } from "@/app/ui/fonts";
import { Provider } from "react-redux";
import store from "./lib/store";

export const metadata: Metadata = {
  title: {
    template: "%s | Next.js Project",
    default: "Next.js Project",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children} </body>
    </html>
  );
}
